name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Start RedisJSON Container
        run: |
          docker run -d --name redis-json -p 6380:6379 redis/redis-stack:latest

      - name: Wait for RedisJSON to be Ready
        run: |
          for i in {1..10}; do
            if redis-cli -p 6380 ping | grep -q PONG; then
              echo "RedisJSON is ready!"
              exit 0
            fi
            echo "Waiting for RedisJSON..."
            sleep 2
          done
          echo "RedisJSON did not start in time!" && exit 1

      - name: Build Server
        run: go build -v -o build/server cmd/server.go

      - name: Build Storage
        run: go build -v -o build/storage cmd/storage.go

      - name: Run Server Tests
        run: MODE=test go test ./server

      - name: Run Package Tests
        run: MODE=test go test ./pkg

      - name: Stop RedisJSON Container
        if: always()
        run: docker stop redis-json && docker rm redis-json